# -*- coding: utf-8 -*-
"""NLP_Sentiment_Analyzer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15EV2NSjk9Y3LCaVXoZzq4yTuBhrdZUGY

### **Connect Drive**
"""

from google.colab import drive
drive.mount('/content/drive')

"""### **Load Dataset**"""

from google.colab import files
files.upload()

!pip install -q kaggle
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

!kaggle datasets download -d lakshmi25npathi/imdb-dataset-of-50k-movie-reviews
!unzip imdb-dataset-of-50k-movie-reviews.zip

"""### **Imports**"""

import re
import pickle
import pandas as pd
from bs4 import BeautifulSoup
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Dropout, Bidirectional
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.callbacks import EarlyStopping
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, f1_score, confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

"""### **Information Dataset**"""

df = pd.read_csv("/content/drive/MyDrive/IMDB Dataset.csv")

df.head()

df.shape

df.info()

"""### **EDA**"""

sentiment_counts = df['sentiment'].value_counts()
plt.pie(sentiment_counts.values, labels=sentiment_counts.index, autopct='%1.1f%%', colors= ['#ffccd9', '#ff99aa'] )
plt.title("Sentiment Distribution")
plt.show()

df['review_length'] = df['review'].apply(lambda x: len(x.split()))
plt.figure(figsize=(6,4))
plt.hist(df['review_length'], bins=50, range=(0,1000), color='#ff99aa')
plt.title("Review Length Distribution")
plt.xlabel("Number of Words")
plt.ylabel("Frequency")
plt.show()

"""### **Preprocessing**"""

df.isnull().sum()

print(df.duplicated().sum())

df.drop_duplicates(inplace=True)

def clean_text(text):
    text = BeautifulSoup(text, "html.parser").get_text()
    text = re.sub(r'[^a-zA-Z]', ' ', text)
    text = text.lower()
    text = re.sub(r'\s+', ' ', text).strip()
    return text

df['review'] = df['review'].apply(clean_text)

df['label'] = df['sentiment'].map({'positive': 1, 'negative': 0})
df.drop('sentiment', axis=1, inplace=True)

df.head()

"""### **Tokenization**"""

tokenizer = Tokenizer(num_words=10000)
tokenizer.fit_on_texts(df['review'])

sequences = tokenizer.texts_to_sequences(df['review'])
padded_sequences = pad_sequences(sequences, maxlen=200)
labels = df['label'].values

with open("tokenizer.pkl", "wb") as f:
    pickle.dump(tokenizer, f)

"""### **Split Train and Test**"""

X_train, X_test, y_train, y_test = train_test_split(padded_sequences, labels, test_size=0.2, random_state=42, stratify=labels)

"""### **Train Model**"""

model = Sequential()
model.add(Embedding(input_dim=10001, output_dim=128, input_length=200))
model.add(LSTM(128, dropout=0.2, recurrent_dropout=0.2))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

early_stop = EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True)
history = model.fit(X_train, y_train,epochs=10,batch_size=64,validation_split=0.1,callbacks=[early_stop],verbose=1)

model.save("/content/drive/MyDrive/LSTM_imdb_model.h5")
with open("/content/drive/MyDrive/LSTM_imdb_history.pkl", "wb") as f:
    pickle.dump(history.history, f)

model = load_model("/content/drive/MyDrive/LSTM_imdb_model.h5")
model.summary()

with open("/content/drive/MyDrive/LSTM_imdb_history.pkl", "rb") as f:
    history = pickle.load(f)
colors = ['#ff99aa', '#7f8c8d']  # بينك فاتح + رمادي متوسط

plt.figure(figsize=(12,4))
plt.subplot(1, 2, 1)
plt.plot(history['accuracy'], color=colors[0], label='Train Accuracy')
plt.plot(history['val_accuracy'], color=colors[1], label='Validation Accuracy')
plt.title("Model Accuracy")
plt.xlabel("Epochs")
plt.ylabel("Accuracy")
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(history['loss'], color=colors[0], label='Train Loss')
plt.plot(history['val_loss'], color=colors[1], label='Validation Loss')
plt.title("Model Loss")
plt.xlabel("Epochs")
plt.ylabel("Loss")
plt.legend()

plt.tight_layout()
plt.show()

"""### **Evaluation**"""

y_pred = model.predict(X_test)
y_pred = (y_pred > 0.5).astype(int)

print(classification_report(y_test, y_pred))

cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(5,4))
sns.heatmap(cm,annot=True,fmt='d',cmap=["#fff0f5", "#ff99aa"],xticklabels=['Negative', 'Positive'],yticklabels=['Negative', 'Positive'])

plt.title("Confusion Matrix")
plt.xlabel("Predicted Label")
plt.ylabel("True Label")
plt.show()

"""## **GUI**"""

!pip install --quiet streamlit pyngrok tensorflow keras bs4 pillow
from pyngrok import ngrok
ngrok.kill()

ngrok.set_auth_token("30U2HAlJQbZebe7blq2x3NNyeJT_23d7hk7aPcVwQEHGzeeLf")

app_code = """
import streamlit as st
import pickle, re
from bs4 import BeautifulSoup
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import load_model

model = load_model("/content/drive/MyDrive/LSTM_imdb_model.h5")
with open("/content/drive/MyDrive/tokenizer.pkl", "rb") as f:
    tokenizer = pickle.load(f)

def clean_text(text):
    text = BeautifulSoup(text, "html.parser").get_text()
    text = re.sub(r'[^a-zA-Z]', ' ', text)
    text = text.lower()
    text = re.sub(r'\\s+', ' ', text).strip()
    return text

st.set_page_config(
    page_title="Movie Sentiment Analyzer",
    page_icon="🎬",
    layout="centered"
)

st.markdown('''
<div style="display:flex; justify-content:center; margin-top:10px;">
    <div style="
        background: linear-gradient(135deg, #667eea, #764ba2);
        width:90px;
        height:90px;
        border-radius:24px;
        display:flex;
        align-items:center;
        justify-content:center;
        font-size:42px;
        box-shadow: 0px 10px 25px rgba(102,126,234,0.4);">🎬</div>
</div>
''', unsafe_allow_html=True)

st.markdown('''
<h2 style="text-align:center; margin-top:14px;">
Movie Sentiment Analyzer
</h2>
<p style="text-align:center; color:#7a869a;">
Analyze the sentiment of any movie review
</p>
''', unsafe_allow_html=True)

review = st.text_area(
    "Your Review",
    height=170,
    placeholder="Write or paste a movie review here..."
)

st.markdown('''
<style>
div.stButton > button {
    background: linear-gradient(135deg, #667eea, #764ba2);
    color: white;
    border: none;
    padding: 0.6em 2.5em;
    border-radius: 14px;
    font-size: 16px;
    font-weight: 500;
    box-shadow: 0px 10px 25px rgba(102,126,234,0.4);
    transition: 0.3s;
}
div.stButton > button:hover {
    transform: translateY(-2px);
    box-shadow: 0px 14px 30px rgba(102,126,234,0.55);
}
</style>
''', unsafe_allow_html=True)

analyze = st.button("Analyze")

if analyze:
    if not review.strip():
        st.warning("Please enter a review")
    else:
        cleaned = clean_text(review)
        seq = tokenizer.texts_to_sequences([cleaned])
        padded = pad_sequences(seq, maxlen=200)
        pred = model.predict(padded)[0][0]

        if pred > 0.5:
            st.success(f"Positive")
        else:
            st.error(f"Negative")

st.markdown('''
<p style="text-align:center; color:#9aa5b1; margin-top:30px;">
 💜 Developed by Hayoma 💜
</p>
''', unsafe_allow_html=True)
"""

with open("app.py", "w") as f:
    f.write(app_code)

ngrok.kill()
public_url = ngrok.connect(8501)
print("Your app is live at:", public_url)

!streamlit run app.py &>/dev/null &